package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IPAMAllocator is an autogenerated mock type for the IPAMAllocator type
type IPAMAllocator struct {
	mock.Mock
}

// Allocate provides a mock function with given fields: ctx, sliceName, clusterName, requiredCIDRSize
func (_m *IPAMAllocator) Allocate(ctx context.Context, sliceName string, clusterName string, requiredCIDRSize int) (string, error) {
	ret := _m.Called(ctx, sliceName, clusterName, requiredCIDRSize)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) string); ok {
		r0 = rf(ctx, sliceName, clusterName, requiredCIDRSize)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, sliceName, clusterName, requiredCIDRSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitializePool provides a mock function with given fields: sliceName, sliceSubnet
func (_m *IPAMAllocator) InitializePool(sliceName, sliceSubnet string) error {
	ret := _m.Called(sliceName, sliceSubnet)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(sliceName, sliceSubnet)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Reclaim provides a mock function with given fields: ctx, sliceName, clusterName
func (_m *IPAMAllocator) Reclaim(ctx context.Context, sliceName string, clusterName string) error {
	ret := _m.Called(ctx, sliceName, clusterName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, sliceName, clusterName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
